# -*- coding: utf-8 -*-
"""Simple_linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZWm-oYj1g22zsGe7HbRaSPZp2P9ZHIs8
"""



pip install scikit-learn

from sklearn import linear_model

dir(linear_model)

from sklearn import datasets

dir(datasets)

boston_data = datasets.load_boston()

print(type(boston_data))

dir(boston_data)

print(boston_data.DESCR)

boston_data.data

boston_data.data.shape

boston_data.data_module

boston_data.feature_names

boston_data.filename

boston_data.target

boston_data.target.shape

import pandas as pd

X = boston_data.data 

df = pd.DataFrame(X , columns= boston_data.feature_names)
df

df.info

df.head(10)

df.size

y = boston_data.target 
df["Price"] = y 
df

df.info

df.describe

lr = linear_model.LinearRegression()

dir(lr)

input = df["RM"] 
output = df["Price"]

import numpy as pd

input = np.array(input).reshape(-1,1)
output = np.array(output).reshape(-1,1)

print(input.shape)
print(output.shape)

lr.coef_

lr.intercept_

lr.score(X,y)

lr.fit(input , output)

lr.predict(input)

lr.predict([['9']])

lr.predict([['20']])

